//
// Created by jk on 2015/7/1.
//

#ifndef ELECTROMBILE_FIRMWARE_THREAD_H
#define ELECTROMBILE_FIRMWARE_THREAD_H

#include <eat_interface.h>

#define THREAD_MAIN      EAT_USER_0
#define THREAD_TIMER     EAT_USER_1
#define TRHEAD_SMS       EAT_USER_2
#define THREAD_VIBRATION EAT_USER_3
#define THREAD_FTP EAT_USER_4
#define THREAD_CAN EAT_USER_5

#endif //ELECTROMBILE_FIRMWARE_THREAD_H
